// Code generated by https://github.com/expgo/ag DO NOT EDIT.
// Plugins:
//   - github.com/expgo/log/annotation

package example

import (
	"github.com/expgo/log"
)

func init() {
	log.Lazy[MyLog]()
}
